title: Bobby Calzaretta's Resume and Project Portfolio
categories: CATEGORY-1 CATEGORY-2

author:
    name: Robert "Bobby" Calzaretta, Jr.
    email: rcalzaretta@berkeley.edu

description: > 
    This page contains selected projects in data science and programing

show_excerpts: false

footer_links:
    linkedin_username: https://www.linkedin.com/in/robert-calzaretta-jr

theme: jekyll-theme-cayman
