title: Bobby Calzaretta's Resume and Project Portfolio
author:
    name: Robert "Bobby" Calzaretta, Jr.
    email: rcalzaretta@berkeley.edu
    linkedin: https://www.linkedin.com/in/robert-calzaretta-jr
    github:  https://github.com/RCalzaretta/

description: > 
    This page contains selected projects of Bobby Calzaretta

show_excerpts: false

theme: jekyll-theme-cayman
