title: Bobby Calzaretta's Resume and Project Portfolio
categories: CATEGORY-1 CATEGORY-2

author:
    name	: Robert "Bobby" Calzaretta, Jr.
    bio		: "Data Science and Programming Portfolio"
    location	: "Oakland, CA"
    email	: "rcalzaretta@berkeley.edu"
    github	: "rcalzaretta"
    linkedin	: "robert-calzaretta-jr"

description: This page contains selected projects in data science and programing


theme: jekyll-theme-cayman
